config/routes.rb
Rails.application.routes.draw do
  resources :articles
  resources :users
  resources :roles do
  	collection do
  		get :hide_roles
  		post :hide_roles_update
  	end
  end
  root :to => "users#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_type.rb
module AdminType
	PAGE_LIMIT = 10
	YES = 0 
	NO = 1
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
	belongs_to :user
	# has_many :images
end

app/models/role.rb
class Role < ApplicationRecord
	def Role.active_roles
		roles = where("is_checked=?", AdminType::NO)
		arr = []
		if roles.present?
			roles.each do |role|
				arr.push(["#{role.name}", role.id])
			end
		end
		arr
	end
end

app/models/user.rb
class User < ApplicationRecord
	# has_many :articles
	# mount_uploader :avatar, AvatarUploader
	serialize :meta_details
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.all
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.fetch(:article, {})
    end
end

app/controllers/roles_controller.rb
class RolesController < ApplicationController
  before_action :set_role, only: [:show, :edit, :update, :destroy]

  # GET /roles
  # GET /roles.json
  def index
    # @roles = Role.all
    if params[:deleted] == "true"
      @roles = Role.where(deleted_flag: true)
    else
      @roles = Role.where(deleted_flag: false)
    end
    @roles_count = @roles.count
    @roles = @roles.paginate(page: params[:page], per_page: AdminType::PAGE_LIMIT)
  end

  # GET /roles/1
  # GET /roles/1.json
  def show
  end

  # GET /roles/new
  def new
    @role = Role.new
  end

  # GET /roles/1/edit
  def edit
  end

  # POST /roles
  # POST /roles.json
  def create
    @role = Role.new(role_params)

    respond_to do |format|
      if @role.save
        format.html { redirect_to @role, notice: 'Role was successfully created.' }
        format.json { render :show, status: :created, location: @role }
      else
        format.html { render :new }
        format.json { render json: @role.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /roles/1
  # PATCH/PUT /roles/1.json
  def update
    respond_to do |format|
      if @role.update(role_params)
        format.html { redirect_to @role, notice: 'Role was successfully updated.' }
        format.json { render :show, status: :ok, location: @role }
      else
        format.html { render :edit }
        format.json { render json: @role.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /roles/1
  # DELETE /roles/1.json
  def destroy
    @role.destroy
    respond_to do |format|
      format.html { redirect_to roles_url, notice: 'Role was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def hide_roles
    @roles = Role.all
  end

  def hide_roles_update
    respond_to do |format|
      if params.present? && params[:roles].present?
        params[:roles].keys.compact! 
        roles = Role.all
        roles.each do |role|
          if (params[:roles].keys.include?("role_#{role.id}"))
            role.is_checked = AdminType::YES
          else
            role.is_checked = AdminType::NO
          end
          if role.save
            format.html{ redirect_to hide_roles_roles_url, notice: "Successfully updated"}
          else
            format.html{ redirect_to hide_roles_roles_url, error: "Successfully updated"}
          end
        end
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_role
      @role = Role.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def role_params
      params.fetch(:role, {})
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    if params[:deleted] == "true"
      @users = User.where(deleted_flag: true)
    else
      @users = User.where(deleted_flag: false)
    end
    @users_count = @users.count
    @users = @users.paginate(page: params[:page], per_page: AdminType::PAGE_LIMIT)
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
    @active_roles = Role.active_roles
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      # params.fetch(:user, {})
      params.require(:user).permit(:first_name, :last_name, :email, :avatar, :deleted_flag, :deleted_at, :user_roles => [])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
		<meta name="description" content="Bootstrap Admin App + jQuery">
		<meta name="keywords" content="app, responsive, jquery, bootstrap, dashboard, admin">
		<title>Lotvue</title>
		<link rel="short icon" type="image/png" href="<%=asset_path "favicon.png"%>">
		<%= csrf_meta_tags %>
		<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
		<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
	</head>
	<body>
		<div class="wrapper">
			<aside class="aside">
				<div class="aside-inner">
					<nav data-sidebar-anyclick-close="" class="sidebar">
						<ul class="nav">
							<li class=" ">
								<a href="<%= users_path %>" title="Users">
									<em class="icon-menu"></em>
									<span>Users</span>
								</a>
								<!-- <ul id="roles" class="nav sidebar-subnav collapse flexcroll">
									<li class="sidebar-subnav-header" style="padding: 4px"></li>
									<li><%#= link_to "Active Users", users_path, {class:"sub_menu1"} %></li>
									<li><%#= link_to "Hide Users", users_path, {class:"sub_menu1"} %></li>
								</ul> -->
							</li>


							<li class=" ">
								<a href="<%= roles_path %>" title="Roles">
									<em class="icon-menu"></em>
									<span>Roles</span>
								</a>
							</li>

							<li class=" ">
								<a href="<%= hide_roles_roles_path %>" title="Hide Roles">
									<em class="icon-menu"></em>
									<span>Hide Roles</span>
								</a>
							</li>

						</ul>
					</nav>
				</div>
			</aside>
			<section>
				<%if notice%>
					<div class="alert alert-success" id="success-alert">
						<button type="button" class="close" data-dismiss="alert">x</button> <%= notice %>
					</div>
				<%end%>
				<%if alert%>
					<div class="alert alert-success" id="success-alert">
						<button type="button" class="close" data-dismiss="alert">x</button> <%= alert %>
					</div>
				<%end%>
				<div id="main-contnet-id">
					<div class="row">
						<%= yield %>
					</div>
				</div>
			</section>
			<!-- Page footer-->
			<footer class="text-center">
				<span>&copy; 2019 - Lotvue</span>
			</footer>
		</div>
	</body>
</html>

app/views/roles/_form.html.erb
<%#= form_for(role) do |f| %>
  <%# if role.errors.any? %>
    <!-- <div id="error_explanation"> -->
      <!-- <h2><%#= pluralize(role.errors.count, "error") %> prohibited this role from being saved:</h2> -->

      <!-- <ul> -->
      <%# role.errors.full_messages.each do |message| %>
        <!-- <li><%#= message %></li> -->
       <%# end %>
      <!-- </ul> -->
    <!-- </div> -->
  <%# end %>

  <!-- <div class="actions"> -->
    <%#= f.submit %>
  <!-- </div> -->
<%# end %>
<div class="col-md-12">
  <div class="panel">
    <div class="panel-heading">
      <h2 class="heading" style="border-bottom:1px solid #ddd;"><%= page_title%></h2>
    </div>
    <div class="panel-body">
      <%= form_for(role, local: true, class: "form-horizontal") do |form| %>
      <% if role.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(role.errors.count, "error") %> prohibited this role from being saved:</h2>
        <ul>
          <% role.errors.full_messages.each do |message| %>
          <li style='color:red'><%= message %></li>
          <% end %>
        </ul>
      </div>
      <% end %>
      
      <div class="col-sm-8">
        <div class="form-group">
          <%= form.label :first_name, 'First Name<span class="text-danger">*</span>'.html_safe, class: "col-lg-3 control-label" %>
          <div class="col-lg-9">
            <%= form.text_field :first_name, :placeholder => "Enter First Name", id: :user_first_name, required: true, class: "form-control" %>
          </div>
        </div>
        <div class="form-group">
          <%= form.label :last_name, 'Last Name<span class="text-danger">*</span>'.html_safe, class: "col-lg-3 control-label" %>
          <div class="col-lg-9">
            <%= form.text_field :last_name, :placeholder => "Enter Last Name", id: :user_last_name, required: true, class: "form-control" %>
          </div>
        </div>
        <div class="form-group">
          <%= form.label :email, 'Email<span class="text-danger">*</span>'.html_safe, class: "col-lg-3 control-label" %>
          <div class="col-lg-9">
            <%= form.email_field :email, :placeholder => "Enter Email", id: :user_email, class: "form-control",:required => true %>
          </div>
        </div>
        <%= hidden_field_tag(:row_count_dates, 0) %>
        <span id="add_first_0">
          <%= link_to "", "javascript: void(0)", onclick: "", :class => "fa fa-plus", :style=>"" %>
        </span> &nbsp;&nbsp;
        <div class="form-group">
          <div class="text-center">
            <%= hidden_field_tag :page, params[:page] %>
            <% button_label = params[:action] == "edit" ? "Update" : "Create"%>
            <%= form.submit "#{button_label}", class: "btn btn-sm btn-info" %>&nbsp;<%= link_to 'Cancel', users_path(page: params[:page]), class: "btn btn-sm btn-default" %>
          </div>
        </div>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/roles/_roles_list.html.erb
<div class="panel-body" style="padding-top: 0">
	<table class="table table-hover table-bordered">
		<thead class="bg-gray">
			<tr>
				<th>Name</th>	
				<th>Status</th>	
				<!-- <th>Action</th>	 -->
			</tr>
		</thead>
		<tbody>
			<% roles.each do |role| %>
				<tr>
					<td><%= role.name %></td>
					<td><%= role.status %></td>
					<!-- <td><%#= role %></td> -->
				</tr>
			<% end %>
		</tbody>
	</table>
</div>

app/views/roles/edit.html.erb
<h1>Editing Role</h1>

<%= render 'form', role: @role %>

<%= link_to 'Show', @role %> |
<%= link_to 'Back', roles_path %>

app/views/roles/hide_roles.html.erb
<%= form_tag url_for(:controller => "roles", :action => "hide_roles_update") do -%>
  <div class="row">
  <div class="col-md-12">
    <div class="panel panel-info">
      <div class="panel-heading panel-padding">
        <h4>Hide Roles for Users</h4>
      </div>   
      <div class="clearfix"></div>      
      <div class="panel-body">
        <% @roles.each do |role| %>
					<% checked_value = role.is_checked == AdminType::YES ? true : false %>
					<div class="col-sm-4 form-group">
						<label>
							<%= check_box_tag "roles[role_#{role.id}]", "1", checked_value, {} %><%= role.name %>
						</label>
					</div>
				<% end %>
      </div>
      <div class="form-group" align = "center">
        <%= submit_tag "update", :class => "btn btn-info btn-xm", id: "submit" %>
        <%= link_to 'Cancel', hide_roles_roles_path, class: "btn btn-sm btn-default" %>
      </div>
    </div>
  </div>
<%end%>

app/views/roles/index.html.erb
<div>
  <div class="col-md-12">
    <div class="panel">
      <div class="panel-heading panel-view">
        <h2 class="heading" style="float:left;border:none;">Roles</h2>
        <div class="pull-right">
          <% if params[:deleted].to_s != "true"%>
            <%= link_to new_role_path(page: params[:page]), class: "btn btn-info" do %>
              <i class="fa fa-plus" aria-hidden="true"></i> New Role
            <% end %>
            <%= link_to roles_path(deleted: true, undeleted_users_page: params[:page]), class: "btn btn-warning btn_style" do %>
              <i class="fa fa-trash" aria-hidden="true"></i> Recycle Bin
            <% end %>
            <% else %>
              <%= link_to roles_path(page: params[:undeleted_users_page]), class: "btn btn-info" do %>
              <i class="fa fa-reply" aria-hidden="true"></i> Roles List
            <% end %>
          <% end %>
        </div>

        <hr style="margin:0 15px">
        <div class="row panel-body">
          <div id="errors_div"></div>
          <div class="col-md-offset-7 col-md-5">
          </div>
        </div>
        <div class="clearfix"></div>
        <div class="table-responsive" id="destination_list">
          <%= render 'roles_list', roles: @roles %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/roles/new.html.erb
<!-- <h1>New Role</h1> -->

<%#= render 'form', role: @role %>

<%#= link_to 'Back', roles_path %>

<%= render 'form', role: @role, page_title: "New User" %>

app/views/roles/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_role_path(@role) %> |
<%= link_to 'Back', roles_path %>

app/views/users/_form.html.erb
<div class="col-md-12">
  <div class="panel">
    <div class="panel-heading">
      <h2 class="heading" style="border-bottom:1px solid #ddd;"><%= page_title%></h2>
    </div>
    <div class="panel-body">
      <%= form_for(user, local: true, class: "form-horizontal") do |form| %>
      <% if user.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>
        <ul>
          <% user.errors.full_messages.each do |message| %>
          <li style='color:red'><%= message %></li>
          <% end %>
        </ul>
      </div>
      <% end %>
      
      <div class="col-sm-8">
        <div class="form-group">
          <%= form.label :first_name, 'First Name<span class="text-danger">*</span>'.html_safe, class: "col-lg-3 control-label" %>
          <div class="col-lg-9">
            <%= form.text_field :first_name, :placeholder => "Enter First Name", id: :user_first_name, required: true, class: "form-control" %>
          </div>
        </div>
        <div class="form-group">
          <%= form.label :last_name, 'Last Name<span class="text-danger">*</span>'.html_safe, class: "col-lg-3 control-label" %>
          <div class="col-lg-9">
            <%= form.text_field :last_name, :placeholder => "Enter Last Name", id: :user_last_name, required: true, class: "form-control" %>
          </div>
        </div>
        <div class="form-group">
          <%= form.label :email, 'Email<span class="text-danger">*</span>'.html_safe, class: "col-lg-3 control-label" %>
          <div class="col-lg-9">
            <%= form.email_field :email, :placeholder => "Enter Email", id: :user_email, class: "form-control",:required => true %>
          </div>
        </div>
        
        <div class="form-group">
          <%= form.label :user_roles, 'Roles', :class => "col-lg-3 control-label" %>
          <div class="col-lg-9">
<% binding.pry %>
            <%= form.select :user_roles, active_roles, {:prompt=>"--Select Role--"}, {:id => :user_user_roles, :class => "form-control", :required =>  true, :style => "width:100%!important;", multiple: true} %>
          </div>
        </div>

        <%= hidden_field_tag(:row_count_dates, 0) %>
        <span id="add_first_0">
          <%= link_to "", "javascript: void(0)", onclick: "", :class => "fa fa-plus", :style=>"" %>
        </span> &nbsp;&nbsp;
        <div class="form-group">
          <div class="text-center">
            <%= hidden_field_tag :page, params[:page] %>
            <% button_label = params[:action] == "edit" ? "Update" : "Create"%>
            <%= form.submit "#{button_label}", class: "btn btn-sm btn-info" %>&nbsp;<%= link_to 'Cancel', users_path(page: params[:page]), class: "btn btn-sm btn-default" %>
          </div>
        </div>
      </div>
      <% end %>
    </div>
  </div>
</div>

<script type="text/javascript">
  var roles = "<%= user.user_roles.blank? ? [] : JSON[user.user_roles].select(&:present?).join(",") %>".split(",");
  $("#user_user_roles").select2().val(roles).trigger('change');
</script>

app/views/users/edit.html.erb
<!-- <h1>Editing User</h1>

<%#= render 'form', user: @user %>

<%#= link_to 'Show', @user %> |
<%#= link_to 'Back', users_path %>
 -->

 <%= render 'form', user: @user, active_roles: @active_roles, page_title: "Edit User" %>

app/views/users/index.html.erb
<div>
  <div class="col-md-12">
    <div class="panel">
      <div class="panel-heading panel-view">
        <h2 class="heading" style="float:left;border:none;">Users</h2>
        <div class="pull-right">
          <% if params[:deleted].to_s != "true"%>
            <%= link_to new_user_path(page: params[:page]), class: "btn btn-info" do %>
              <i class="fa fa-plus" aria-hidden="true"></i> New User
            <% end %>
            <%= link_to users_path(deleted: true, undeleted_users_page: params[:page]), class: "btn btn-warning btn_style" do %>
              <i class="fa fa-trash" aria-hidden="true"></i> Recycle Bin
            <% end %>
          <% else %>
            <%= link_to users_path(page: params[:undeleted_users_page]), class: "btn btn-info" do %>
              <i class="fa fa-reply" aria-hidden="true"></i> Users List
            <% end %> 
          <% end %>
        </div>
      </div>
      <hr style="margin:0 15px">
      <div class="clearfix"></div>
      <div class="panel-body">
        <div class="table-responsive">
          <table id="datatable2" class="table table-hover table-bordered">
            <thead class="bg-gray">
              <tr>
                <th>First Name</th>
                <th>Last Name</th>
                <th>Email</th>
              </tr>
            </thead>
            <tbody>
              <% @users.each do |user| %>
                <%
                  if params[:deleted].to_s == "true"
                    user_show_path = users_path(user, deleted: params[:deleted], page: params[:page], undeleted_users_page: params[:undeleted_users_page])
                  else
                    user_show_path = user_path(user, deleted: params[:deleted], page: params[:page])
                  end
                %>
                <tr>
                  <td><%= user.first_name %></td>
                  <td><%= user.last_name %></td>
                  <td><%= user.email %></td>
                </tr>
              <% end %>
            </tbody>
          </table>
          <br>
        </div>
      </div>
      <span class="text_black blink"><b><%= pluralize(@users_count, "User") %></b> </span>
      <div class="text-center">
      <%= will_paginate @users, renderer: BootstrapPagination::Rails %>
      </div>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<%= render 'form', user: @user, active_roles: @active_roles, page_title: "New User" %>

app/views/users/show.html.erb
<div class="col-md-12">
  <div class="panel">
    <div class="panel-heading">
      <h2 class="heading" style="border-bottom:1px solid #ddd">User Show</h2>
    </div>
    <div class="panel-body">
      <div class="col-md-offset-2 col-md-10">
        <dl class="dl-horizontal">
          <dt>First Name:</dt>
          <dd><%= @user.first_name %></dd>
          <dt>Last Name:</dt>
          <dd><%= @user.last_name %></dd>
          <dt>Email:</dt>
          <dd><%= @user.email %></dd>
          <% if params[:deleted].to_s != "true"%>
            <dt class="action_btn">
              <%= link_to 'Edit', edit_user_path(@user, page: params[:page]), class: "btn btn-sm btn-info"  %>
            </dt>
            <dd class="action_btn">
              <%= link_to 'Close', users_path(page: params[:page]), class: "btn btn-sm btn-default" %>
            </dd>
          <% else %>
            <dd class="action_btn_delete">
              <%= link_to 'Close', users_path(deleted: params[:deleted], page: params[:page], undeleted_users_page: params[:undeleted_users_page]), class: "btn btn-sm btn-default" %>
            </dd>
          <% end %>
        </dl>
      </div>
    </div>
  </div>
</div>